# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ExampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleApp

  #NEXTOME SDK 
  pod 'PhoenixSdk_x86', :path => '../'
  pod 'NextomeLegacy_x86', :path => '../'
  pod 'Toast-Swift', '~> 5.0.1'
  
  #OTHER
  pod 'PKHUD', '~> 5.0'

  
end
